name: orderly
services:
  db:
    image: mysql:9.3
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: ${APP_TIMEZONE:-Europe/Madrid}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 5s
      retries: 10
      interval: 5s
      start_period: 40s

  spring-boot:
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    container_name: spring-boot
    restart: always
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}
      TZ: ${APP_TIMEZONE:-Europe/Madrid}
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    depends_on:
      db:
        condition: service_healthy
  
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    restart: always
    env_file: .env
    ports:
      - "${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}"
    depends_on:
      - spring-boot
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
