name: REST API Tests (H2)

on:
  push:
    paths:
      - 'app/spring-boot/**'

jobs:
  test-rest-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Maven tests
        working-directory: app/spring-boot
        run: mvn -B test
